version: '3.8'

services:
  krayin-db:
    image: 'mysql:8.0'
    container_name: krayin-db
    restart: unless-stopped
    labels:
      - "coolify.exclude=true" 
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: krayin
      MYSQL_USER: krayin
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - krayin_db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "krayin", "-p${DB_PASSWORD}"]
      interval: 30s
      retries: 5
    networks:
      - krayin-network

  krayin:
    image: 'webkul/krayin:v2.1.2-https'
    container_name: krayin-app
    restart: unless-stopped
    labels:
      - "coolify.main=true"
      - "coolify.name=Krayin CRM"
    ports:
      - '${APP_PORT:-8082}:80'
    volumes:
      - krayin_storage:/var/www/html/laravel-crm
      - krayin_uploads:/var/www/html/public/uploads
    depends_on:
      krayin-db:
        condition: service_healthy
    networks:
      - krayin-network
    command: >
      sh -c "
        echo 'Starting Krayin CRM...' &&
        sleep 20 &&
        
        # Para MySQL interno se existir
        pkill -f mysql 2>/dev/null || true &&
        
        # Testa conexão com banco
        until php /var/www/html/laravel-crm/artisan migrate:status &>/dev/null; do
          echo 'Waiting for database...'
          sleep 5
        done &&
        
        # Limpa cache
        php /var/www/html/laravel-crm/artisan config:clear &&
        php /var/www/html/laravel-crm/artisan cache:clear &&
        
        # Migrations
        php /var/www/html/laravel-crm/artisan migrate --force &&
        
        # Primeira instalação?
        if ! php /var/www/html/laravel-crm/artisan tinker --execute='echo DB::table(\"users\")->count() > 0 ? \"exists\" : \"empty\";' 2>/dev/null | grep -q 'exists'; then
          echo 'First time setup...' &&
          php /var/www/html/laravel-crm/artisan db:seed --force &&
          php /var/www/html/laravel-crm/artisan passport:install --force &&
          php /var/www/html/laravel-crm/artisan passport:client --personal --no-interaction &&
          echo 'Setup complete!'
        fi &&
        
        # Storage link e permissões
        php /var/www/html/laravel-crm/artisan storage:link &&
        chown -R www-data:www-data /var/www/html/laravel-crm/storage &&
        
        # Inicia Apache
        echo 'ServerName localhost' >> /etc/apache2/apache2.conf &&
        exec apache2ctl -D FOREGROUND
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      start_period: 120s

volumes:
  krayin_storage:
  krayin_uploads:
  krayin_db_data:

networks:
  krayin-network: