version: '3.8'

services:
  krayin-app:
    image: webkul/krayin:2.0.1
    container_name: krayin_app
    restart: unless-stopped
    ports:
      - "80:8082"
    volumes:
      - krayin-app-data:/var/www/html
    depends_on:
      - krayin-mysql
    networks:
      - krayin-network

  krayin-mysql:
    image: mysql:8.0
    container_name: krayin_mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=krayin
      - MYSQL_USER=krayin_user
      - MYSQL_PASSWORD=oM3J6czR6dXg5ZHc0d
    volumes:
      - krayin-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - krayin-network

  krayin-phpmyadmin:
    image: phpmyadmin:latest
    container_name: krayin_phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_HOST=krayin-mysql
      - PMA_USER=krayin_user
      - PMA_PASSWORD=krayin_password
    ports:
      - "8080:80"
    depends_on:
      - krayin-mysql
    networks:
      - krayin-network

volumes:
  krayin-app-data:
  krayin-mysql-data:

networks:
  krayin-network:
    driver: bridge