version: '3.8'

services:
  krayin-db:
    image: 'mysql:8.0'
    container_name: krayin-db
    restart: unless-stopped
    labels:
      - "coolify.exclude=true" 
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-RV2yYmv6mxKzIAv}
      MYSQL_DATABASE: ${DB_DATABASE:-krayin}
      MYSQL_USER: ${DB_USERNAME:-krayin}
      MYSQL_PASSWORD: ${DB_PASSWORD:-pefvon-wuMcoz-8qupqe}
    volumes:
      - krayin_db_data:/var/lib/mysql
      - ./mysql-init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --innodb-buffer-pool-size=256M
    healthcheck:
      test:
        - CMD
        - sh
        - -c
        - 'mysqladmin ping -h localhost -u ${DB_USERNAME:-krayin} -p${DB_PASSWORD:-pefvon-wuMcoz-8qupqe}'
      interval: 20s
      timeout: 10s
      retries: 20
      start_period: 90s
    networks:
      - krayin-network

  krayin-init:
    image: 'webkul/krayin:v2.1.2-https'
    container_name: krayin-init
    labels:
      - "coolify.exclude=true" 
    # NOTA: Este serviço é apenas para inicialização - SEM portas expostas
    volumes:
      - krayin_storage:/var/www/html/laravel-crm
    environment:
      DB_CONNECTION: ${DB_CONNECTION:-mysql}
      DB_HOST: krayin-db
      DB_PORT: ${DB_PORT:-3306}
      DB_DATABASE: ${DB_DATABASE:-krayin}
      DB_USERNAME: ${DB_USERNAME:-krayin}
      DB_PASSWORD: ${DB_PASSWORD:-pefvon-wuMcoz-8qupqe}
      APP_KEY: ${APP_KEY}
      APP_ENV: ${APP_ENV:-production}
      APP_DEBUG: ${APP_DEBUG:-false}
      DEBUGBAR_ENABLED: ${DEBUGBAR_ENABLED:-false}
      APP_URL: ${APP_URL}
      APP_TIMEZONE: ${APP_TIMEZONE:-America/Sao_Paulo}
      CACHE_DRIVER: ${CACHE_DRIVER:-file}
      SESSION_DRIVER: ${SESSION_DRIVER:-file}
      QUEUE_CONNECTION: ${QUEUE_CONNECTION:-database}
      LOG_CHANNEL: ${LOG_CHANNEL:-stack}
      LOG_LEVEL: ${LOG_LEVEL:-error}
    depends_on:
      krayin-db:
        condition: service_healthy
    networks:
      - krayin-network
    command: >
      sh -c "
        echo 'Krayin CRM Initialization Started...' &&
        
        # Aguardar banco estar completamente pronto
        echo 'Waiting for database to be fully ready...' &&
        sleep 60 &&
        
        # Verificar se já foi inicializado
        if [ ! -f /var/www/html/laravel-crm/.initialized ]; then
          echo 'First time setup - configuring Krayin CRM...' &&
          
          # Testar conexão com banco antes de prosseguir
          echo 'Testing database connection...' &&
          timeout 30 php /var/www/html/laravel-crm/artisan tinker --execute='
            try {
              DB::connection()->getPdo();
              echo \"Database connection successful\n\";
            } catch (Exception \$$e) {
              echo \"Connection failed: \" . \$$e->getMessage() . \"\n\";
              exit(1);
            }
          ' &&
          
          echo 'Running database migrations...' &&
          php /var/www/html/laravel-crm/artisan migrate --force &&
          
          echo 'Seeding database with initial data...' &&
          php /var/www/html/laravel-crm/artisan db:seed --force &&
          
          echo 'Creating storage symbolic link...' &&
          php /var/www/html/laravel-crm/artisan storage:link &&
          
          echo 'Setting proper permissions...' &&
          chown -R www-data:www-data /var/www/html/laravel-crm/storage &&
          chown -R www-data:www-data /var/www/html/laravel-crm/bootstrap/cache &&
          chmod -R 775 /var/www/html/laravel-crm/storage &&
          chmod -R 775 /var/www/html/laravel-crm/bootstrap/cache &&
          
          # Marcar como inicializado
          touch /var/www/html/laravel-crm/.initialized &&
          echo 'Krayin CRM initialization completed successfully!' 
        else
          echo 'Krayin CRM already initialized, skipping setup.'
        fi &&
        
        echo 'Initialization container finished.'
      "
    restart: "no"

  krayin:
    image: 'webkul/krayin:v2.1.2-https'
    container_name: krayin-app
    restart: unless-stopped
    # NOTA: Este é o serviço PRINCIPAL - ÚNICO que deve ter domínio no Coolify
    labels:
      - "coolify.main=true"      # Marca como serviço principal
      - "coolify.name=Krayin CRM" # Nome amigável na UI
    ports:
      - '${APP_PORT:-8082}:80'
    volumes:
      - krayin_storage:/var/www/html/laravel-crm
      - krayin_uploads:/var/www/html/public/uploads
    environment:
      DB_CONNECTION: ${DB_CONNECTION:-mysql}
      DB_HOST: krayin-db
      DB_PORT: ${DB_PORT:-3306}
      DB_DATABASE: ${DB_DATABASE:-krayin}
      DB_USERNAME: ${DB_USERNAME:-krayin}
      DB_PASSWORD: ${DB_PASSWORD:-pefvon-wuMcoz-8qupqe}
      APP_KEY: ${APP_KEY}
      APP_ENV: ${APP_ENV:-production}
      APP_DEBUG: ${APP_DEBUG:-false}
      DEBUGBAR_ENABLED: ${DEBUGBAR_ENABLED:-false}
      APP_URL: ${APP_URL}
      APP_TIMEZONE: ${APP_TIMEZONE:-America/Sao_Paulo}
      CACHE_DRIVER: ${CACHE_DRIVER:-file}
      SESSION_DRIVER: ${SESSION_DRIVER:-file}
      QUEUE_CONNECTION: ${QUEUE_CONNECTION:-database}
      LOG_CHANNEL: ${LOG_CHANNEL:-stack}
      LOG_LEVEL: ${LOG_LEVEL:-error}
      APP_CIPHER: ${APP_CIPHER:-AES-256-CBC}
    depends_on:
      krayin-db:
        condition: service_healthy
      krayin-init:
        condition: service_completed_successfully
    networks:
      - krayin-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  krayin_storage:
    driver: local
  krayin_uploads:
    driver: local
  krayin_db_data:
    driver: local

networks:
  krayin-network:
    driver: bridge
