version: '3.8'

services:
  krayin-db:
    image: 'mysql:8.0'
    container_name: krayin-mysql
    restart: unless-stopped
    labels:
      - "coolify.exclude=true"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: krayin
      MYSQL_USER: krayin
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - krayin_mysql_data:/var/lib/mysql
    networks:
      - krayin-network

  krayin:
    image: 'webkul/krayin:v2.1.2-https'
    container_name: krayin-app
    restart: unless-stopped
    labels:
      - "coolify.main=true"
      - "coolify.name=Krayin CRM"
    ports:
      - '${APP_PORT:-8082}:80'
    volumes:
      - krayin_workspace:/var/www/html/
    environment:
      # Database Configuration
      DB_CONNECTION: mysql
      DB_HOST: krayin-mysql
      DB_PORT: 3306
      DB_DATABASE: krayin
      DB_USERNAME: krayin
      DB_PASSWORD: ${DB_PASSWORD}
      
      # App Configuration
      APP_KEY: ${APP_KEY}
      APP_ENV: ${APP_ENV:-production}
      APP_DEBUG: ${APP_DEBUG:-false}
      APP_URL: ${APP_URL}
      APP_TIMEZONE: ${APP_TIMEZONE:-America/Sao_Paulo}
    depends_on:
      - krayin-db
    networks:
      - krayin-network

  krayin-phpmyadmin:
    image: phpmyadmin:latest
    container_name: krayin-phpmyadmin
    restart: unless-stopped
    labels:
      - "coolify.exclude=true"
    environment:
      PMA_HOST: krayin-mysql
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
    ports:
      - '8080:80'
    depends_on:
      - krayin-db
    networks:
      - krayin-network

volumes:
  krayin_workspace:
    driver: local
  krayin_mysql_data:
    driver: local

networks:
  krayin-network:
    driver: bridge
