version: '3.8'

services:
  krayin-db:
    image: 'mysql:8.0'
    container_name: krayin-db
    restart: unless-stopped
    labels:
      - "coolify.exclude=true" 
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: krayin
      MYSQL_USER: krayin
      MYSQL_PASSWORD: ${DB_PASSWORD}
      # Forçar recriação quando senhas mudarem (opcional)
      MYSQL_INITDB_SKIP_TZINFO: 1
    volumes:
      - krayin_db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "krayin", "-p${DB_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s
    networks:
      - krayin-network

  krayin:
    image: 'webkul/krayin:v2.1.2-https'
    container_name: krayin-app
    restart: unless-stopped
    labels:
      - "coolify.main=true"
      - "coolify.name=Krayin CRM"
    ports:
      - '${APP_PORT:-8082}:80'
    volumes:
      - krayin_storage:/var/www/html/laravel-crm
      - krayin_uploads:/var/www/html/public/uploads
    environment:
      # Aplicação
      APP_KEY: ${APP_KEY}
      APP_ENV: ${APP_ENV:-production}
      APP_DEBUG: ${APP_DEBUG:-false}
      DEBUGBAR_ENABLED: ${DEBUGBAR_ENABLED:-false}
      APP_URL: ${APP_URL}
      APP_TIMEZONE: ${APP_TIMEZONE:-America/Sao_Paulo}
      APP_CIPHER: ${APP_CIPHER:-AES-256-CBC}
      
      # Banco externo
      DB_CONNECTION: mysql
      DB_HOST: krayin-db
      DB_PORT: 3306
      DB_DATABASE: krayin
      DB_USERNAME: krayin
      DB_PASSWORD: ${DB_PASSWORD}
      
      # Cache e sessão
      CACHE_DRIVER: ${CACHE_DRIVER:-file}
      SESSION_DRIVER: ${SESSION_DRIVER:-file}
      QUEUE_CONNECTION: ${QUEUE_CONNECTION:-database}
      LOG_CHANNEL: ${LOG_CHANNEL:-stack}
      LOG_LEVEL: ${LOG_LEVEL:-error}
    depends_on:
      krayin-db:
        condition: service_healthy
    networks:
      - krayin-network
    command: >
      sh -c "
        echo 'Waiting for database...' &&
        sleep 30 &&
        
        # Parar MySQL interno se estiver rodando
        supervisorctl stop mysql 2>/dev/null || true &&
        
        # Reset de senha se necessário (preserva dados)
        echo 'Checking database connection...' &&
        if ! timeout 10 php /var/www/html/laravel-crm/artisan tinker --execute='
          try {
            DB::connection()->getPdo();
            echo \"Connection OK\n\";
          } catch (Exception \$$e) {
            echo \"Connection failed, may need password reset\n\";
            exit(1);
          }
        '; then
          echo 'Connection failed - trying to reset MySQL password...' &&
          docker exec krayin-db mysql -u root -p\${MYSQL_ROOT_PASSWORD} -e \"
            ALTER USER 'krayin'@'%' IDENTIFIED BY '\${DB_PASSWORD}';
            FLUSH PRIVILEGES;
          \" 2>/dev/null || echo 'Password reset attempted'
        fi &&
        
        # Verificar conexão novamente
        echo 'Testing final connection...' &&
        timeout 30 php /var/www/html/laravel-crm/artisan tinker --execute='
          try {
            DB::connection()->getPdo();
            echo \"Database connection successful\n\";
          } catch (Exception \$$e) {
            echo \"Connection failed: \" . \$$e->getMessage() . \"\n\";
            exit(1);
          }
        ' &&
        
        # Executar migrações se necessário
        php /var/www/html/laravel-crm/artisan migrate --force &&
        
        # Configurar permissões
        chown -R www-data:www-data /var/www/html/laravel-crm/storage &&
        chmod -R 775 /var/www/html/laravel-crm/storage &&
        
        echo 'Starting Apache...' &&
        exec apache2ctl -D FOREGROUND
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 180s

volumes:
  krayin_storage:
    driver: local
  krayin_uploads:
    driver: local
  krayin_db_data:
    driver: local

networks:
  krayin-network:
    driver: bridge
