version: '3.8'

services:
  krayin-db:
    image: 'mysql:8.0'
    container_name: krayin-db
    restart: unless-stopped
    labels:
      - "coolify.exclude=true"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: krayin
      MYSQL_USER: krayin
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - krayin_db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "krayin", "-p${DB_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - krayin-network

  krayin:
    image: 'webkul/krayin:v2.1.2-https'
    container_name: krayin-app
    restart: unless-stopped
    labels:
      - "coolify.main=true"
      - "coolify.name=Krayin CRM"
    ports:
      - '${APP_PORT:-8082}:80'
    volumes:
      - krayin_storage:/var/www/html/laravel-crm/storage
      - krayin_uploads:/var/www/html/laravel-crm/public/uploads
    environment:
      # Aplicação
      APP_KEY: ${APP_KEY}
      APP_ENV: ${APP_ENV:-production}
      APP_DEBUG: ${APP_DEBUG:-false}
      APP_URL: ${APP_URL}
      APP_TIMEZONE: ${APP_TIMEZONE:-America/Sao_Paulo}
      
      # Banco de dados
      DB_CONNECTION: mysql
      DB_HOST: krayin-db
      DB_PORT: 3306
      DB_DATABASE: krayin
      DB_USERNAME: krayin
      DB_PASSWORD: ${DB_PASSWORD}
      
      # Cache e sessão
      CACHE_DRIVER: file
      SESSION_DRIVER: file
      QUEUE_CONNECTION: database
      
      # Logs
      LOG_CHANNEL: stack
      LOG_LEVEL: error
    depends_on:
      krayin-db:
        condition: service_healthy
    networks:
      - krayin-network
    entrypoint: ["/bin/sh", "-c", "echo 'Krayin CRM Starting...' && sleep 30 && supervisorctl stop mysql 2>/dev/null || true && service mysql stop 2>/dev/null || true && pkill -f mysql 2>/dev/null || true && echo 'Preparando ambiente...' && mkdir -p /var/www/html/laravel-crm/storage/framework/{cache,sessions,views} && mkdir -p /var/www/html/laravel-crm/storage/logs && chmod -R 777 /var/www/html/laravel-crm/storage && echo 'Atualizando .env...' && sed -i \"s/DB_HOST=.*/DB_HOST=krayin-db/g\" /var/www/html/laravel-crm/.env && sed -i \"s/DB_USERNAME=.*/DB_USERNAME=krayin/g\" /var/www/html/laravel-crm/.env && sed -i \"s/DB_PASSWORD=.*/DB_PASSWORD=${DB_PASSWORD}/g\" /var/www/html/laravel-crm/.env && echo 'Testing database connection...' && until php -r \"\\$conn = new mysqli('krayin-db', 'krayin', '${DB_PASSWORD}', 'krayin'); if (\\$conn->connect_error) { exit(1); } echo 'DB OK'; exit(0);\" >/dev/null 2>&1; do echo 'Waiting for database...'; sleep 5; done && echo 'Database connected!' && php /var/www/html/laravel-crm/artisan cache:clear && php /var/www/html/laravel-crm/artisan migrate --force && USER_COUNT=$(php /var/www/html/laravel-crm/artisan tinker --execute=\"echo DB::table('users')->count();\" 2>/dev/null | tail -1) && if [ \"$USER_COUNT\" = \"0\" ] || [ -z \"$USER_COUNT\" ]; then echo 'First installation - running seeders and API setup...' && php /var/www/html/laravel-crm/artisan db:seed --force && php /var/www/html/laravel-crm/artisan passport:install --force && echo 'Installation complete!'; else echo \"System already initialized ($USER_COUNT users found)\"; fi && php /var/www/html/laravel-crm/artisan storage:link 2>/dev/null || true && chown -R www-data:www-data /var/www/html/laravel-crm/storage && chmod -R 777 /var/www/html/laravel-crm/storage && echo 'ServerName localhost' >> /etc/apache2/apache2.conf && echo 'Starting Apache...' && exec apache2ctl -D FOREGROUND"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s

volumes:
  krayin_storage:
    driver: local
  krayin_uploads:
    driver: local
  krayin_db_data:
    driver: local

networks:
  krayin-network:
    driver: bridge