version: '3.8'

services:
  krayin-db:
    image: 'mysql:8.0'
    container_name: krayin-db
    restart: unless-stopped
    labels:
      - "coolify.exclude=true" 
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: krayin
      MYSQL_USER: krayin
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - krayin_db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "krayin", "-p${DB_PASSWORD}"]
      interval: 30s
      retries: 5
    networks:
      - krayin-network

  krayin:
    image: 'webkul/krayin:v2.1.2-https'
    container_name: krayin-app
    restart: unless-stopped
    labels:
      - "coolify.main=true"
      - "coolify.name=Krayin CRM"
    ports:
      - '${APP_PORT:-8082}:80'
    volumes:
      - krayin_storage:/var/www/html/laravel-crm
      - krayin_uploads:/var/www/html/public/uploads
    depends_on:
      krayin-db:
        condition: service_healthy
    networks:
      - krayin-network
    command: >
      sh -c "
        echo 'Starting Krayin CRM...' &&
        cd /var/www/html/laravel-crm &&
        sleep 20 &&
        
        # Para MySQL interno se existir
        pkill -f mysql 2>/dev/null || true &&
        
        # Verifica se artisan existe
        if [ ! -f artisan ]; then
          echo 'ERROR: artisan file not found!'
          ls -la /var/www/html/
          exit 1
        fi &&
        
        # Fix composer issues
        export COMPOSER_ALLOW_SUPERUSER=1 &&
        composer dump-autoload --no-scripts --optimize 2>/dev/null || true &&
        
        # Aguarda banco
        until php artisan migrate:status &>/dev/null; do
          echo 'Waiting for database...'
          sleep 5
        done &&
        
        # Limpa cache
        php artisan config:clear &&
        php artisan cache:clear &&
        php artisan route:clear || true &&
        php artisan view:clear || true &&
        
        # Migrations
        php artisan migrate --force &&
        
        # Primeira instalação? (método mais simples)
        if ! php artisan tinker --execute='echo DB::table(\\\"users\\\")->exists() ? \\\"yes\\\" : \\\"no\\\";' 2>/dev/null | grep -q 'yes'; then
          echo 'First time setup...' &&
          php artisan db:seed --force &&
          php artisan passport:install --force --no-interaction &&
          php artisan passport:client --personal --no-interaction --name=KrayinPersonalClient &&
          echo 'Setup complete!'
        fi &&
        
        # Storage link e permissões
        php artisan storage:link &&
        chown -R www-data:www-data storage bootstrap/cache &&
        chmod -R 775 storage bootstrap/cache &&
        
        # Inicia Apache
        echo 'ServerName localhost' >> /etc/apache2/apache2.conf &&
        exec apache2ctl -D FOREGROUND
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      start_period: 120s

volumes:
  krayin_storage:
  krayin_uploads:
  krayin_db_data:

networks:
  krayin-network: